trigger: none

steps:
- script: npm install
  displayName: npm install

- script: npx ng build --project oang --prod
  displayName: ng build oang

- script: npx ng build --project oang-material --prod
  displayName: ng build oang-material

- script: npx ng build --project demo --prod
  displayName: ng build demo

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pago pelo Uso - Gui(4a6fb573-2012-4afb-a35a-1f37db594180)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload-batch --account-name cblxoang -d `$web -s dist/demo'

