name: Publish demo

on:
  push:
    branches: [ demo ]

jobs:
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Runs a single command using the runners shell
    - run: npm ci
    - run: npx ng build --project oang --prod
    - run: npx ng build --project oang-material --prod
    - run: npx ng build --project demo --prod
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: 'az storage blob upload-batch --account-name cblxoang -d $web -s dist/demo'
