# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish packages to npm

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npx ng build --project oang --prod
      - run: npx ng build --project oang-material --prod
      - run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - run: echo $RELEASE_VERSION
      - run: npm version $RELEASE_VERSION --no-git-tag-version
        working-directory: dist/oang
      - run: npm version $RELEASE_VERSION --no-git-tag-version
        working-directory: dist/oang-material
      
      # PUBLISH  
      - run: npm publish
        working-directory: dist/oang
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          
      - run: npm publish
        working-directory: dist/oang-material
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

#   publish-npm:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 12
#           registry-url: https://registry.npmjs.org/
#       - run: npm ci
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.npm_token}}

#   publish-gpr:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 12
#           registry-url: https://npm.pkg.github.com/
#       - run: npm ci
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
